### ISSUE TITLE
ask what bundle to attach field to by default

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/fields_generator#21]
right now automatically attaches to organism

**Comment by bradfordcondon** [comment]
#26 removed organism and replaced it with a variable the user should supply

**Comment by risharde** [comment]
Hi bradford, where is this variable? I've just generated a sample but the field does not appear in my bundle

**Comment by bradfordcondon** [comment]
hi @risharde : adding full automation for these was a bit much, unfortunately.  Since sometimes you'll want your field to attach to multiple bundles in different ways....  still, i think i can improve the stubs more to point users to where to fill in this information.

for the field to attach to your bundle, you need to tell tripal about it in hook `fields_info` and `bundle_instances_info`.  

So for example, here we tell it to attach to organism:

https://github.com/statonlab/fields_generator/blob/cb73134dffdd0feb7da5987a4154300cf8c73c64/stubs/tripal_fields#L40
