### ISSUE TITLE
How to attach newly generated field to bundle?

### ISSUE THREAD

**Issue by risharde** [statonlab/fields_generator#40]
Hi @bradfordcondon , I don't understand how to attach the generated field to my specific bundle. I can't seem to locate information/documentation regarding this, can you help me out? Thanks!

**Comment by bradfordcondon** [comment]
hi @risharde : you should make sure you are attaching your field in the the  [module_name].fields.inc file
You can see in the chado_fields the variable `$my_data_table`, when set, will tell it which data table ot attach to.
https://github.com/statonlab/fields_generator/blob/cb73134dffdd0feb7da5987a4154300cf8c73c64/stubs/chado_fields#L40

so if $my_data_table is organsim, the field will attach to the organism bundle.

If you havent, i strongly recommend you read through the fields documentation in the tripal dev guide.  It's really tough to wrap your head around it at first.

http://tripal.info/tutorials/v3.x/developers_handbook/custom-field

**Comment by bradfordcondon** [comment]
hi @risharde sorry I was on vacation when i responded ot this so spaced the question.

Did my explanation answer your question?

**Comment by bradfordcondon** [comment]
hi @risharde im assuming you've got this sorted out.  If not, please let me know and ill reopen.
